apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      run: comprehensive-production-ci-cd-pipeline
  template:
    metadata:
      labels:
        run: comprehensive-production-ci-cd-pipeline
    spec:
      containers:
      - name: comprehensive-production-ci-cd-pipeline
        image: mohamedesmael/comprehensive-production-ci-cd-pipeline:1.0.0-18
	resources:
	 limits:
	  memory: "256Mi"
	  cpu: "500n"
        ports:
          - containerPort: 8080


